### ISSUE TITLE
400 Error 

### ISSUE THREAD

**Issue by RainySoft** [brettwooldridge/influx4j#1]
I use the following code to read around 1M CSV data then write to influx DB. 

InfluxDB.builder().setConnection("IP",port,InfluxDB.protocol.HTTP).setUsername("xxx").setDataBase("Test").setThreadFactory(new DaemonThreadFactory("Flusher")).setPrecision().build();
for (CSVRecord r:  list) {
  Point p = pointFrom(r); 
 influxDB.write(p);
}

But I keep get 400 and 500 error. any ideas?

**Comment by brettwooldridge** [comment]
What hare the error messages included with the HTTP errors?

**Comment by brettwooldridge** [comment]
@RainySoft It seems that InfluxDB may have an internal limitation of 5000 points per-batch insert.  influx4j does not cut off the batch at this point, and so may attempt to insert more than that in a single operation -- and therefore encounters an error.  I'll add a limitation in this weekend and cut a new release.  I'll let you know when it is published.
